// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1V2WavwaKIKXK9fUz2h_NIiTo7gflc2I',
    appId: '1:841284743284:web:921437f6aca4077a98e121',
    messagingSenderId: '841284743284',
    projectId: 'lovebites-7bb03',
    authDomain: 'lovebites-7bb03.firebaseapp.com',
    storageBucket: 'lovebites-7bb03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpZml3xkhjGV9xL7t1FTryjUwERrH6Mso',
    appId: '1:841284743284:android:7696bd9a0a80872598e121',
    messagingSenderId: '841284743284',
    projectId: 'lovebites-7bb03',
    storageBucket: 'lovebites-7bb03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqfVCP1UMIppWnonHqRNaxg4IwMPtk6lU',
    appId: '1:841284743284:ios:6c7dabd770ec022b98e121',
    messagingSenderId: '841284743284',
    projectId: 'lovebites-7bb03',
    storageBucket: 'lovebites-7bb03.appspot.com',
    iosBundleId: 'com.example.loveBitesUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqfVCP1UMIppWnonHqRNaxg4IwMPtk6lU',
    appId: '1:841284743284:ios:ea140ca0bc26eea898e121',
    messagingSenderId: '841284743284',
    projectId: 'lovebites-7bb03',
    storageBucket: 'lovebites-7bb03.appspot.com',
    iosBundleId: 'com.example.loveBitesUserApp.RunnerTests',
  );
}
